package com.app.feja.mooddiary.constant;


public enum WEATHER {
    SUNNY, CLEAR, FAIR, CLOUDY, PARTLY_CLOUDY, MOSTLY_CLOUDY, OVERCAST, SHOWER,
    THUNDERSHOWER, THUNDERSHOWER_WITH_HAIL, LIGHT_RAIN, MODERATE_RAIN, HEAVY_RAIN,
    STORM, HEAVY_STORM, SEVERE_STORM, ICE_RAIN, SLEET, SNOW_FLURRY, LIGHT_SNOW,
    MODERATE_SNOW, HEAVY_SNOW, SNOWSTORM, DUST, SAND, DUSTSTORM, SANDSTORM, FOGGY,
    HAZE, WINDY, BLUSTERY, HURRICANE, TROPICAL_STORM, TORNADO, COLD, HOT, UNKNOWN


}
