package com.app.feja.mooddiary.constant;


public enum WEATHER {
    SUNNY(0), CLEAR(1), FAIR(2), CLOUDY(3), PARTLY_CLOUDY(4), MOSTLY_CLOUDY(5), OVERCAST(6),
    SHOWER(7), THUNDERSHOWER(8), THUNDERSHOWER_WITH_HAIL(9), LIGHT_RAIN(10), MODERATE_RAIN(11),
    HEAVY_RAIN(12), STORM(13), HEAVY_STORM(14), SEVERE_STORM(15), ICE_RAIN(16), SLEET(17),
    SNOW_FLURRY(18), LIGHT_SNOW(19), MODERATE_SNOW(20), HEAVY_SNOW(21), SNOWSTORM(22), DUST(23),
    SAND(24), DUSTSTORM(25), SANDSTORM(26), FOGGY(27), HAZE(28), WINDY(29), BLUSTERY(30),
    HURRICANE(31), TROPICAL_STORM(32), TORNADO(33), COLD(34), HOT(35), UNKNOWN(36);

    private int index;

    WEATHER(int i) {
        this.index = i;
    }

    public int getIndex() {
        return index;
    }

}
